baseURL: "http://example.org/"
languageCode: "en-us"
title: "example"

params:
  author:
    name: "example"
    homepage: "https://example.com"

markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: true
    tabWidth: 4
    style: "algol_nu"
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: true

menu:
  main:
    - name: "Posts"
      url: "/posts/"
      weight: 1
    - name: "Tags"
      url: "/tags/"
      weight: 2

build:
  writeStats: true

frontmatter:
  date: ["date", "publishDate", "lastmod"]
  expiryDate: ["expiryDate"]
  lastmod: [":git", "lastmod", "date", "publishDate"]
  publishDate: ["publishDate", "date"]

caches:
  images:
    dir: ":cacheDir/images"
